(defun my-csharp-mode-hook ()
  (define-key omnisharp-mode-map (kbd "<C-tab>") 'omnisharp-auto-complete)
  (define-key omnisharp-mode-map "." 'omnisharp-add-dot-and-auto-complete)
  (setq company-idle-delay 0)
  (setq company-minimum-prefix-length 2)
  (setq company-selection-wrap-around t)
  (electric-pair-mode 1))
(add-hook 'csharp-mode-hook 'my-csharp-mode-hook)
(add-hook 'csharp-mode-hook 'omnisharp-mode)
(add-hook 'csharp-mode-hook 'yas-minor-mode)
(add-hook 'csharp-mode-hook 'company-mode)
(setq omnisharp-server-executable-path "~/omnisharp-server/OmniSharp/bin/Debug/OmniSharp.exe")
